title:             Innovator's Log
email:             stanislav.siska@deutsche-boerse.com
description:       Exploring and discovering
author:            Start Bootstrap
baseurl:           "/blog"
url:               "https://innovation-lab.cz"
permalink:         "/:categories/:title:output_ext"

# Social Profiles
twitter_username:  InnoLab
github_username:   InnoLabGit
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:  
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - circle.yml
